/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ProjectEuler

import MultiplesOf3and5

fun main(args: Array<String>) {
    val multiplesOf3and5 = MultiplesOf3and5()
    multiplesOf3and5.solve(1000)
}
